### ISSUE TITLE
trying to implement ldita-bootstrap.lunr in the bootstrap ditaot plugin but facing some error

### ISSUE THREAD

**Issue by Gurushesh-Metapercept** [infotexture/dita-bootstrap.lunr#23]
[gen-index-json] Result: 1
[gen-index-json] node:internal/modules/cjs/loader:1325
[gen-index-json]     throw err;
[gen-index-json]     ^
[gen-index-json]
[gen-index-json] SyntaxError: C:\Users\Admin\AppData\Local\Temp\temp20231019184255754\lunr.json: Unexpected token G in JSON at position 38
[gen-index-json]     at parse (<anonymous>)
[gen-index-json]     at Module._extensions..json (node:internal/modules/cjs/loader:1322:39)
[gen-index-json]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[gen-index-json]     at Module._load (node:internal/modules/cjs/loader:958:12)
[gen-index-json]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[gen-index-json]     at require (node:internal/modules/cjs/helpers:110:18)
[gen-index-json]     at Object.<anonymous> (C:\Users\Admin\AppData\Local\Temp\temp20231019184255754\null10407635299677372326:10:19)
[gen-index-json]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
[gen-index-json]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
[gen-index-json]     at Module.load (node:internal/modules/cjs/loader:1117:32)
[gen-index-json]
[gen-index-json] Node.js v18.15.0
Error: Lunr.js failed to generate search index

**Comment by lakokkonen** [comment]
Hi Gurushesh,

Did you figure this out already? I have encountered the same issue, and been trying to debug it.

I suspect this has something to do with the file paths created by the plugin. They contain a mix of forward and backslashes, and when a backslash is combined with a certain letter (G in your case, for me it was S), the JSON parsing fails and the index is not created. It's a case of JSON escape characters. 

Here's a screenshot of the invalid JSON file in my test case. You can see that all first level file paths are correct, but more than one level deep all the slashes are backslashes, which the JSON parser tries to interpret as escape characters:

![jsonfail](https://github.com/infotexture/dita-bootstrap.lunr/assets/108674366/41290da6-18a8-45b8-9909-43c913ae80b2)

If you want to confirm this, try building a simple test map with topics in only one folder. The build should work ok.

**Comment by jason-fox** [comment]
I suspect this is a combination of two things:

1. Building an index on Windows.
2. Building an index with deeply embedded folders.

That would leave JSON `\` within the `link` elements, which would be interpreted as escape codes as  @lakokkonen described.

Would a simple ANT `<replace>`  and/or XSL `replace()` be sufficient to fix this?  See: https://github.com/infotexture/dita-bootstrap.lunr/compare/develop...jason-fox:dita-bootstrap.lunr:feature/slash

```console
dita uninstall fdita-bootstrap.lunr
dita install https://github.com/jason-fox/fdita-bootstrap.lunr/archive/feature/slash.zip
```

Since I don't run on Windows, I can't reproduce this test case.

**Comment by lakokkonen** [comment]
With the fix @jason-fox provided the build doesn't fail.

However, the file paths in **preview.json** still contain the `\`, so the JSON contains errors: 

![jsonfail2](https://github.com/infotexture/dita-bootstrap.lunr/assets/108674366/9527122a-efa2-4713-868c-dd087af203e1)

In this case, the search is unable to find the topic with the corrupted link. Otherwise the search works OK..

**Comment by jason-fox** [comment]
That just requires the same fix to be applied to the other file. see [here](https://github.com/infotexture/dita-bootstrap.lunr/commit/8eb1695ab1b75f9b27dbf29d195a5c72bf45092c) - try pulling again.

**Comment by lakokkonen** [comment]
Works like a charm now. The JSON is valid and the search is working.
